# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('nick_name', models.CharField(default='', max_length=200)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('profile_picture_path', models.FilePathField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
