# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.RenameField(
            model_name='member',
            old_name='register_date',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='nick_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='profile_picture_path',
        ),
        migrations.AddField(
            model_name='member',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
